### ISSUE TITLE
The USD dollar sign icon isn't working

### ISSUE THREAD

**Issue by halloffame** [driftyco/ionic-creator-issues#218] opened 2015-04-28 20:28 UTC
I'm trying to use the `ion-social-usd` icon and it shows up in the dropdown menu but when I select it, it just shows up as a rectagle. The same thing happens for `ion-social-usd-outline`. All the other icons I tried worked normally.

<img src="https://cloud.githubusercontent.com/assets/957859/7379433/bdc1952c-eda9-11e4-9bd8-66ff924a4bf9.png" alt="screen shot 2015-04-28 at 1 22 30 pm" width="332">

**Comment by matthewkremer** [comment] 2015-06-03 19:01
Duplicate of #45, I'll be looking into this as well as tabs in general soon :+1:

**Closed by matthewkremer** 2015-06-03 19:01 UTC

**Comment by halloffame** [comment] 2015-06-04 16:41
awesome thanks!
