### ISSUE TITLE
Switching Between Projects Shows Blank Screen/Page

### ISSUE THREAD

**Issue by hollyschinsky** [driftyco/ionic-creator-issues#35] opened 2014-10-09 02:47 UTC
When switching between projects, the project you select to open will show a blank screen though there's content in it. No page is selected at this point, but selecting the first page or something within it will still not display content. Clicking to another page then back will display it. The 2 screenshots below show the initial open followed by selecting a page that contains content but still displays blank. Also, going to the project section panel and selecting the same project that is open causes the same behavior. **Note:** If the *2nd* page is selected first, it appears to display as expected. 

![project-switched-initial-open](https://cloud.githubusercontent.com/assets/359935/4570418/91c0c4c4-4f5d-11e4-8879-8ade99436980.png)

![project-switched-first-page-selected](https://cloud.githubusercontent.com/assets/359935/4570419/9332e800-4f5d-11e4-83cd-a5a367fd2d25.png)

**Comment by matthewkremer** [comment] 2015-06-03 19:07
Duplicate of #11, fixed :+1:

**Closed by matthewkremer** 2015-06-03 19:07 UTC
