### ISSUE TITLE
Project not deleted

### ISSUE THREAD

**Issue by shlomis** [driftyco/ionic-creator-issues#145] opened 2014-12-03 14:08 UTC
Created a test project, tried deleting it entered "yes" or "YES" clicked OK. nothing happened.
project ID "256ff1a8401a"
![image](https://cloud.githubusercontent.com/assets/1629257/5281568/7f702bc2-7b07-11e4-99d9-05e363859ea6.png)

**Comment by bhargavy** [comment] 2015-01-16 09:54
I'm having the same issue, Project is not being being deleted.

**Comment by matthewkremer** [comment] 2015-06-03 19:32
Duplicate of #57

**Closed by matthewkremer** 2015-06-03 19:32 UTC
