### ISSUE TITLE
Header and Footer margins should be containers

### ISSUE THREAD

**Issue by birbilis** [driftyco/ionic-creator-issues#283] opened 2015-10-21 14:08 UTC
When turning on a Header and Footer margin, one should be able to drop controls in them and also adjust their height (with a knob similar to the one the Spacer control has). The Page should have Header and Footer toggle buttons (better not just called margins)

Should also be able to programatically show/hide the header/footer (when they're hidden should not remove their child controls from the DOM, just have their parent [header or footer div] node collapsed so that they hide too)

**Comment by matthewkremer** [comment] 2015-10-21 15:55
Closed as duplicate of #75. We're definitely looking at adding in support for this.

**Closed by matthewkremer** 2015-10-21 15:55 UTC
