### ISSUE TITLE
Сan not add items to the header or footer

### ISSUE THREAD

**Issue by norgen** [driftyco/ionic-creator-issues#109] opened 2014-11-12 17:13 UTC
Trying to add a text box in the page header, but it is impossible. The guide has such markings. Sorry for bad English.

**Comment by matthewkremer** [comment] 2015-06-03 19:57
Closed as a (somewhat) duplicate of #75. I'll look into expanding the header when working on that issue. Thanks!

**Closed by matthewkremer** 2015-06-03 19:57 UTC
