### ISSUE TITLE
Validation for routing URL

### ISSUE THREAD

**Issue by pmsteil** [driftyco/ionic-creator-issues#226] opened 2015-06-05 11:30 UTC
Need some validation for the routing URL for a page.  I entered a value with a leading @ instead of / and all seemed fine until I went to "Test" the app, then I just got a black screen.

**Comment by matthewkremer** [comment] 2015-06-05 15:13
Closing as a (pretty much) duplicate of #87. I'll definitely be taking a look at this one sometime, as I fell for it too when clicking around.

**Closed by matthewkremer** 2015-06-05 15:13 UTC
