### ISSUE TITLE
Can't seem to drag anything into Footer margin

### ISSUE THREAD

**Issue by pmsteil** [driftyco/ionic-creator-issues#228] opened 2015-06-05 11:37 UTC
I turned on the footer margin for a page and wanted to drag my button bar into it, but I can't seem to drag anything into the footer.

**Comment by matthewkremer** [comment] 2015-06-05 15:14
Closing this as a (kind of) duplicate of #75. It is on my list to improve the header and footer functionality :+1:

**Closed by matthewkremer** 2015-06-05 15:14 UTC
