### ISSUE TITLE
Change routing URL breaks linked buttons

### ISSUE THREAD

**Issue by pmsteil** [driftyco/ionic-creator-issues#225] opened 2015-06-05 11:28 UTC
I am a newb here, so keep that in mind. :)  Great tool so far.

When I changed the routing url for a page, the button that was tied to it didn't automatically recognize the change.  Had to go select the proper routing url again.

**Comment by matthewkremer** [comment] 2015-06-05 15:12
Hey @pmsteil :) Thanks for taking the time to check out Creator and submit some issues! It's much appreciated.

Closing this one as a duplicate of #95, I'll be taking a look at your others too.

**Closed by matthewkremer** 2015-06-05 15:12 UTC
