### ISSUE TITLE
ion-happy icon doesn't show

### ISSUE THREAD

**Issue by stavinopolis** [driftyco/ionic-creator-issues#201] opened 2015-03-31 17:54 UTC
When changing a tab icon to ion-happy, creator shows an empty square in place of the icon. Not sure if this effects the implementation or not but other icons work fine.

**Comment by matthewkremer** [comment] 2015-06-03 19:02
Duplicate of #45, I'll be looking into this as well as tabs in general soon :+1:

**Closed by matthewkremer** 2015-06-03 19:02 UTC
