### ISSUE TITLE
Drag and drop Input not working and button cannot be add in heading

### ISSUE THREAD

**Issue by Jerome2606** [driftyco/ionic-creator-issues#222] opened 2015-05-26 14:04 UTC
Hi,

I try to use the creator but when I want to add input on my page is does'nt work.
I test on chrome and firefox latest version (Chrome: Version 43.0.2357.65 m)

here's console log:
```
Drag start input
ionic-creator.js?8:3 Drag start button
2ionic-creator.js?8:3 Drag start input
2ionic-creator.js?8:3 Drag start button
ionic-creator.js?8:2 SCRIPTING Object {action: "appendChild", parent: Object, child: Object}
ionic-creator.js?8:2 Marking id button 1
ionic-creator.js?8:3 DESIGNER: SAVING
ionic-creator.js?8:2 APP OUTLINE
ionic-creator.js?8:2 1  page5
ionic-creator.js?8:2 2   button1
ionic-creator.js?8:2 Identifying 4 components
ionic-creator.js?8:3 Can't find any component with id app1$.getById @ ionic-creator.js?8:3f @ ionic-creator.js?8:2(anonymous function) @ ionic-creator.js?8:2(anonymous function) @ ionic.bundle.js:21655completeOutstandingRequest @ ionic.bundle.js:11865(anonymous function) @ ionic.bundle.js:12166
ionic-creator.js?8:2 Couldn't identify component for app1f @ ionic-creator.js?8:2(anonymous function) @ ionic-creator.js?8:2(anonymous function) @ ionic.bundle.js:21655completeOutstandingRequest @ ionic.bundle.js:11865(anonymous function) @ ionic.bundle.js:12166
ionic-creator.js?8:3 Active component Object {isPlaceholder: undefined, id: "button1", parent: Object, $rendered: button.button.button-stable.button-block.ic-selected}
ionic-creator.js?8:3 Rendering component button1
ionic-creator.js?8:3 PROPERTIES CATS Object {"": Array[4]}
ionic-creator.js?8:3 Rendered properties [jQuery.fn.init[1]]
ionic-creator.js?8:3 SELECT MODEL 
ionic-creator.js?8:3 SELECT MODEL button-block
ionic-creator.js?8:3 SELECT MODEL button-stable
ionic-creator.js?8:2 Rendering from nav Object {id: "nav3", parent: Object, $rendered: div}
ionic-creator.js?8:2 <div>
    <div>
        <ion-nav-bar class="bar-stable">
            <ion-nav-back-button class="button-icon icon ion-ios7-arrow-back">Back</ion-nav-back-button>
        </ion-nav-bar>
        <ion-nav-view></ion-nav-view>
    </div>
</div>
```

Drag start input is ok but I can't drop it on screen.
My second question is how to add back button to heading ?

Thanks

**Comment by matthewkremer** [comment] 2015-06-03 20:59
Hey @Jerome2606 :)

Inputs (and other form elements) can only be added to the "Form" drop target from the Components bar on the left. So first drag a "Form" element over and then an "Input" element into that Form. I'm going to work on making this more obvious or changing the behavior.

As for the buttons in header, duplicate of #75 :)

Thanks!
Matt

**Closed by matthewkremer** 2015-06-03 20:59 UTC

**Comment by CoDEmanX** [comment] 2015-10-06 13:55
If you want to use a range slider for a media player, you would want that to be placed near the bottom, without a surrounding form field - just saying.
