### ISSUE TITLE
Scroll down when inserting several elements

### ISSUE THREAD

**Issue by andailie** [driftyco/ionic-creator-issues#254] opened 2015-08-11 01:41 UTC
I am trying to insert more elements on the phone screen, but it will not let me scroll down and view more than the actual phone screen display size
![picture3](https://cloud.githubusercontent.com/assets/13739862/9188303/26b2d4d0-401e-11e5-8fa3-57c11eeee256.jpg)

**Comment by mkstayalive** [comment] 2015-09-19 01:56
I am facing this issue as well.

**Comment by matthewkremer** [comment] 2015-10-15 14:33
I reworked some of the scrolling in the major release on Tuesday, can you please confirm that this is no longer an issue?

Thanks,
Matt

**Comment by saulocamposi** [comment] 2015-11-01 05:07
I have had the same problem, I can't scroll down my screen .  Is there shortcut for that ? 

https://scontent-mia1-1.xx.fbcdn.net/hphotos-xap1/v/t1.0-9/12141728_1115813778429284_5697571027128160592_n.jpg?oh=6f8942097d7c2c8a4aa90286e204418f&oe=56CB0693

**Comment by matthewkremer** [comment] 2015-11-01 14:02
What browser and version are you using?

**Comment by hemgui** [comment] 2015-12-07 21:26
Same issue chrome 47.0
Cannot scrolldown in both mode edition/preview
same issue in share view.

**Comment by matthewkremer** [comment] 2015-12-07 21:30
I'm still unable to reproduce this, even though I'm running Chrome 47. Are you all on Windows 8.1? I'm downloading an image to test in Windows 8.1 now, I can't reproduce it in Windows 10 either.

**Comment by matthewkremer** [comment] 2015-12-07 22:03
@hemgui Any chance it works now? (Changed something small, probably wont fix it, but thought it'd be worth a shot)

**Comment by hemgui** [comment] 2015-12-07 22:10
![image](https://cloud.githubusercontent.com/assets/6715911/11641247/816a4f04-9d37-11e5-8928-a894dc701c5d.png)
That's good now in desktop, thanks a lot.

**Closed** 2015-12-07 22:27 UTC
