### ISSUE TITLE
Tabs icon lost in edit mode

### ISSUE THREAD

**Issue by sgulci** [driftyco/ionic-creator-issues#215] opened 2015-04-28 06:40 UTC
in tabs page when i click tabs in Page side container icons get invisible

![ioniccreatorbug](https://cloud.githubusercontent.com/assets/3424995/7364046/9bdb70dc-ed8a-11e4-926a-ab30a3ac4228.png)

**Comment by erinmays** [comment] 2015-05-04 19:29
seconded

**Comment by novarac23** [comment] 2015-05-12 20:07
Yep. And I can not post different content on different pages of tabs because it always pulls me back to the first tab.

**Comment by aloncarmel** [comment] 2015-05-14 08:52
same here. SUPER annoying.

**Comment by matthewkremer** [comment] 2015-06-03 18:47
Duplicate of #26, this is definitely high on my list to look into.

**Closed by matthewkremer** 2015-06-03 18:47 UTC
